# See https://starship.rs/config/

# A minimal left prompt
format = """$character"""
# And move the rest of the prompt to the right
right_format = """$all"""

# Inserts a blank line between shell prompts
add_newline = false

[character]
success_symbol = " 🤡"
error_symbol = " 🙈"

[docker_context]
disabled = false

[kubernetes]
disabled = true

[memory_usage]
threshold = 90
disabled = false

[ruby]
disabled = true
