# See https://starship.rs/config/

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# A minimal left prompt
format = """$character"""
# And move the rest of the prompt to the right
right_format = """$all"""

# Inserts a blank line between shell prompts
add_newline = false

[character]
success_symbol = " 🤡"
error_symbol = " 🙈"

[direnv]
disabled = true

[kubernetes]
disabled = true

[memory_usage]
threshold = 90
disabled = false

[ruby]
disabled = true

[nodejs]
detect_files = [".node-version", ".nmvrc"]
detect_folders = []

[php]
detect_extensions = []
detect_files = [".phpbrewrc", ".php-version"]
detect_folders = []

[python]
disabled = true  # VERY slow with pyenv...
#pyenv_version_name = true
# Do not show the current package
format = 'via [${symbol}${pyenv_prefix}(${version} )]($style)'

[package]
disabled = true

[gcloud]
disabled = true

[dotnet]
detect_extensions = []
detect_files = ["global.json"]
detect_folders = []

[aws]
#force_display = true

[docker_context]
disabled = true
