# See https://starship.rs/config/

[memory_usage]
disabled = false

[docker_context]
disabled = false

[kubernetes]
disabled = false

[php]
disabled = true

[ruby]
disabled = true

[aws]
disabled = true

[status]
disabled = false
